# Generated by Django 4.0.5 on 2022-06-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('N', 'Not Submitted'), ('Y', 'Submitted')], default='N', max_length=1),
        ),
    ]
