# Generated by Django 4.0.5 on 2022-06-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_participant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='last_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
