# Generated by Django 4.0.5 on 2022-07-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_tutorial_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfetimage',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
