# Generated by Django 4.0.5 on 2022-07-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0007_uploadedfetimage_created_at'), ('api', '0008_alter_uploadedfetimage_created_at')]

    dependencies = [
        ('api', '0006_user_tutorial_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfetimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
