# Generated by Django 4.0.5 on 2022-07-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_uploadedfetimage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfetimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
