# Generated by Django 4.0.5 on 2022-07-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_uploadedfetimage_created_at_squashed_0008_alter_uploadedfetimage_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfetimage',
            old_name='image',
            new_name='original_image',
        ),
        migrations.AddField(
            model_name='uploadedfetimage',
            name='extracted_image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/extracted/'),
        ),
    ]
